name: "build and test"

on:
  push:
    branches:
      - "main"
    paths:
      - "lib/**"
      - "test/**"
  workflow_dispatch:
  # schedule:
  #   # Prime the caches every Monday
  #   - cron: 0 1 * * MON

permissions: "read-all"

jobs:
  build-and-test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v4"
      - name: "setup ocaml"
        uses: "ocaml/setup-ocaml@v2"
        with:
          ocaml-compiler: "5.0"
          dune-cache: true
      - name: "opam eval"
        run: "eval $(opam env)"
      - name: "install dependencies"
        run: "opam install . --deps-only --with-test"
      - name: "build"
        run: "dune build"
      - name: "test"
        run: "dune test"
      - name: "coverage"
        run: |
          "dune test --instrument-with bisect_ppx --force"
          "bisect-ppx-report summary"
